version: "3"

services:
  server-fan-speed:
    image: hetorusnl/python-poetry
    container_name: server-fan-speed
    env_file: config.env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    entrypoint: /code/run-server-fan-speed.sh
